<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-71NK5AF" name="com.webappsecurity.tests.AccountActivityTest" tests="7" failures="1" timestamp="23 Sep 2019 21:05:04 GMT" time="62.572" errors="0">
  <testcase name="adddata" time="24.884" classname="com.webappsecurity.tests.AccountActivityTest"/>
  <testcase name="adddata" time="18.065" classname="com.webappsecurity.tests.AccountActivityTest"/>
  <testcase name="adddata" time="19.284" classname="com.webappsecurity.tests.AccountActivityTest"/>
  <testcase name="verify_description" time="0.049" classname="com.webappsecurity.tests.AccountActivityTest">
    <failure type="java.lang.AssertionError" message="Description is not entered or is not matching expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Description is not entered or is not matching expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.webappsecurity.tests.AccountActivityTest.verify_description(AccountActivityTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_description -->
  <testcase name="verify_date" time="0.096" classname="com.webappsecurity.tests.AccountActivityTest"/>
  <testcase name="verify_amount" time="0.040" classname="com.webappsecurity.tests.AccountActivityTest"/>
  <testcase name="verify_typeoftrans" time="0.154" classname="com.webappsecurity.tests.AccountActivityTest"/>
</testsuite> <!-- com.webappsecurity.tests.AccountActivityTest -->
